// Simulated data for fake live stream

export const TWITCH_USERNAMES = [
  "xXDarkSlayerXx", "PixelWizard42", "NeonKnight99", "ShadowMage_",
  "CyberPunk2077", "LunaStarlight", "BlazeFury", "IceQueen_",
  "ThunderBolt_X", "MysticRaven", "CosmicDust42", "PhantomBlade",
  "SilverFox_", "CrimsonWolf", "EmeraldEye", "GoldenEagle99",
  "VioletStorm", "ObsidianKing", "RubyHeart_", "SapphireSky",
  "microwave_oven2", "lactose_enjoye", "yurifan1269", "antaresgalax",
  "PinkPandaBubblez", "BocaBola", "neko_sompi", "TenSterakdary",
  "gamer_girl_99", "speedrun_king", "chill_vibes_only", "retro_gamer",
  "nightowl_stream", "coffee_and_code", "pixel_artist", "music_maker",
  "art_streamer", "cozy_gamer", "competitive_pro", "casual_player",
];

export const BILIBILI_USERNAMES = [
  "小明同学", "快乐水手", "星空下的猫", "代码诗人",
  "游戏达人Pro", "美食探索者", "音乐小天才", "画画的小鱼",
  "读书的蜗牛", "旅行的风", "摄影爱好者", "电影迷弟",
  "科技前沿", "历史爱好者", "数学小王子", "化学实验员",
  "生物观察者", "地理探险家", "文学少女", "哲学思考者",
  "二次元少年", "动漫达人", "cosplay小能手", "手办收藏家",
  "vup_fan", "live_lover", "danmaku_master", "gift_sender",
];

export const CHAT_MESSAGES = [
  "lets gooo!", "pog", "poggers", "W stream", "nice play!",
  "lol", "haha", "omg", "no way", "thats insane",
  "first time here, love the vibe", "been watching for 2 hours",
  "can you say hi to me?", "hello from Brazil!", "hi from Japan!",
  "this is so relaxing", "perfect background stream", "love this",
  "how long have you been playing?", "what setup do you use?",
  "your content is amazing", "keep it up!", "youre the best",
  "subscribed!", "just followed!", "lets gooo team",
  "gg", "ez clap", "that was close", "wow", "incredible",
  "can we get some Ws in chat", "W", "W W W", "L take",
  "this is underrated", "why is this not bigger", "deserves more viewers",
  "chat is moving so fast", "cant even read chat lol",
  "anyone else here at 3am?", "insomnia gang rise up",
  "this helps me focus tbh", "study stream vibes",
  "pogchamp", "monkaS", "Kappa", "LUL", "PepeLaugh",
  "based", "no cap", "fr fr", "real", "facts",
  "drop the playlist", "what song is this?", "name the track",
  "how do I get better at this?", "any tips?", "tutorial when?",
  "been here since the beginning", "OG viewer", "day 1",
  "love the community here", "best chat on the platform",
  "sending love from Korea", "hello from Germany!", "UK rep!",
  "this is my comfort stream", "always comes back to this",
  "you missed a spot lol", "nice combo!", "thats the move",
  "I tried this yesterday", "same strategy works for me",
  "can you play something else?", "this game is underrated",
  "the graphics are so good", "sound design is incredible",
  "just got here, what did I miss?", "catch me up chat",
  "this is peak content", "nothing beats this", "10/10",
  "underrated streamer", "should be partner by now",
  "the production quality tho", "so professional",
  "how many hours have you put in?", "dedication is real",
  "respect the grind", "hustle never stops",
  "chat move so slow today", "where is everyone?",
  "lets hype this up!", "spam some emotes!",
  "good luck!", "you got this!", "believe in yourself",
  "this is therapeutic", "so calming", "zen mode activated",
  "perfect for studying", "background noise on point",
  "any other students here?", "exam season survival stream",
  "this keeps me company", "less lonely with this on",
  "the vibes are immaculate", "aesthetic stream",
  "how do I support you?", "where do I donate?",
  "take my money!", "shut up and take my bits",
  "best decision to click on this", "algorithm blessed me today",
  "random recommendation but no regrets", "glad I stayed",
  "this is what the platform needs more of",
  "quality over quantity", "small streamer but big talent",
  "discovered this channel last week, hooked ever since",
  "notification squad where you at?", "bell gang!",
  "the editing on this is clean", "so polished",
  "any merch?", "I would buy merch", "drop the merch link",
  "collab with X would be insane", "dream collab",
  "this deserves to go viral", "sharing this with everyone",
  "my friends need to see this", "sending the link rn",
  "how is this not trending?", "algorithm is broken",
  "underrated content creator", "future big streamer",
  "remember this moment when they hit 100k", "early gang",
  "I was here before it was cool", "hipster viewer",
  "the community is so wholesome", "no toxicity here",
  "positive vibes only", "good energy",
  "this made my day", "needed this today",
  "perfect timing, just got home", "wind down stream",
  "goodnight chat!", "see you tomorrow!", "same time tomorrow?",
  "consistency is key", "never miss a stream",
  "the dedication is admirable", "true professional",
  "any new viewers, hit that follow!", "help grow the community",
  "raiding from another stream", "brought 50 viewers!",
  "this is cozy", "hygge vibes", "comfort content",
  "like a warm blanket", "digital comfort food",
  "this is my happy place", "home screen",
  "the chat is so friendly", "everyone is so nice here",
  "found my new favorite stream", "bookmarked!",
  "added to favorites", "notification bell activated",
  "this is art", "pure art", "masterpiece",
  "the attention to detail", "so much effort",
  "you can tell they care", "passion project",
  "this is what love looks like", "labor of love",
  "keep doing what youre doing", "dont change a thing",
  "perfection", "flawless", "impeccable taste",
];

export const BILIBILI_MESSAGES = [
  "666666", "哈哈哈", "太厉害了", "牛逼！", "太强了吧",
  "爱了爱了", "这也太好玩了", "笑死我了", "绝了", "yyds",
  "前方高能", "名场面", "经典永流传", "泪目了", "破防了",
  "好家伙", "离谱", "不可思议", "太真实了", "是我本人",
  "来了来了", "打卡", "每日必看", "已关注", "三连了",
  "投币了", "收藏了", "转发", "分享", "推荐",
  "这个up主太棒了", "宝藏up主", "被发现了", "火钳刘明",
  "前排", "沙发", "板凳", "地板", "地下室",
  "弹幕护体", "高能预警", "非战斗人员撤离", "前方核能",
  "awsl", "xswl", "dbq", "nsdd", "zqsg",
  "kdl", "szd", "bhys", "u1s1", "有一说一",
  "确实", "没毛病", "合理", "没毛病老铁", "安排",
  "奥利给", "干就完了", "冲！", "加油！", "你可以的！",
  "这也太可爱了吧", "萌化了", "心都要化了", "好治愈",
  "看了一整天", "停不下来", "根本停不下来", "再来亿遍",
  "已加入循环", "单曲循环", "无限循环中", "出不去了",
  "这个bgm好好听", "求歌名", "BGM是什么", "音乐太好听了",
  "画质好高", "太清晰了", "4K好评", "画质感人",
  "更新太慢了", "催更催更", "gkd", "搞快点", "生产队的驴",
  "下次一定", "这次一定", "下次一定一定", "已经三连了",
  "白嫖不好", "投币支持", "充电支持", "已充电",
  "这个系列太好看了", "追更中", "等更新等得好辛苦",
  "评论区人才多", "评论比视频好看", "热评第一",
  "课代表来了", "总结：太好看了", "太长不看版",
  "进度条撑住", "不要停", "继续继续", "还没看够",
  "这个角度绝了", "镜头感太好了", "构图完美",
  "色彩搭配好好看", "审美在线", "太有品味了",
  "细节拉满", "细节怪", "强迫症福音",
  "这个转场太丝滑了", "剪辑太棒了", "后期辛苦了",
  "一个人做的？太厉害了", "团队作品？", "一个人就是一个团队",
  "致敬", "respect", "瑞思拜", "respect bro",
  "这个创意绝了", "脑洞大开", "想象力丰富",
  "看了三遍才看懂", "信息量好大", "需要二刷",
  "已加入学习清单", "马住", "mark", "先马后看",
  "这个教程太实用了", "学到了", "涨知识了",
  "感谢分享", "好人一生平安", "好人卡+1",
  "已推荐给朋友", "安利成功", "成功种草",
  "这个必须火", "不火没天理", "火了踢我",
  "百万播放预定", "热门预定", "上热门",
  "太有梗了", "梗王", "造梗机器",
  "这个表情绝了", "截屏了", "已做成表情包",
  "笑到肚子疼", "笑出鹅叫", "哈哈哈哈哈哈",
  "太感动了", "眼泪不争气地流下来", "泪奔",
  "这就是青春啊", "青春回来了", "爷青回",
  "时代的眼泪", "回忆杀", "童年回忆",
  "太有共鸣了", "说到心坎里了", "扎心了",
  "这个观点我同意", "说得太对了", "无法反驳",
  "有理有据", "逻辑清晰", "分析到位",
  "专业！", "太专业了", "大佬受我一拜",
  "这个数据太震撼了", "不敢相信", "难以置信",
  "刷新认知", "打开新世界的大门", "原来如此",
  "涨姿势了", "get到了", "学到了新知识",
];

export const GIFTS = [
  { name: "Bits", icon: "", value: 100, color: "#9146ff" },
  { name: "Sub", icon: "⭐", value: 500, color: "#9146ff" },
  { name: "Hype Train", icon: "", value: 1000, color: "#f5a623" },
  { name: "Raid", icon: "️", value: 2000, color: "#eb0400" },
  { name: "Mega Bits", icon: "💎💎", value: 5000, color: "#00f593" },
  { name: "Legend Sub", icon: "👑", value: 10000, color: "#ffd700" },
];

export const BILIBILI_GIFTS = [
  { name: "辣条", icon: "️", value: 1, color: "#fb7299" },
  { name: "小心心", icon: "❤️", value: 1, color: "#fb7299" },
  { name: "荧光棒", icon: "🪄", value: 10, color: "#00a1d6" },
  { name: "可乐", icon: "🥤", value: 50, color: "#eb0400" },
  { name: "蛋糕", icon: "🎂", value: 100, color: "#fc9a3c" },
  { name: "火箭", icon: "🚀", value: 500, color: "#9146ff" },
  { name: "飞船", icon: "🛸", value: 1000, color: "#00f593" },
  { name: "金舰长", icon: "👑", value: 5000, color: "#ffd700" },
];

export const STICKERS = [
  { id: "cat-ears", emoji: "", name: "Cat Ears" },
  { id: "crown", emoji: "👑", name: "Crown" },
  { id: "glasses", emoji: "😎", name: "Cool Glasses" },
  { id: "heart", emoji: "❤️", name: "Heart" },
  { id: "star", emoji: "⭐", name: "Star" },
  { id: "fire", emoji: "🔥", name: "Fire" },
  { id: "rainbow", emoji: "", name: "Rainbow" },
  { id: "party", emoji: "🎉", name: "Party" },
  { id: "music", emoji: "🎵", name: "Music" },
  { id: "game", emoji: "🎮", name: "Game" },
  { id: "coffee", emoji: "☕", name: "Coffee" },
  { id: "book", emoji: "📚", name: "Study" },
  { id: "rocket", emoji: "🚀", name: "Rocket" },
  { id: "diamond", emoji: "💎", name: "Diamond" },
  { id: "lightning", emoji: "⚡", name: "Lightning" },
  { id: "flower", emoji: "🌸", name: "Flower" },
];

export const FILTERS = [
  { id: "none", name: "Original", css: "none" },
  { id: "warm", name: "Warm", css: "sepia(0.3) saturate(1.4) brightness(1.05)" },
  { id: "cool", name: "Cool", css: "saturate(0.8) brightness(1.1) hue-rotate(10deg)" },
  { id: "vintage", name: "Vintage", css: "sepia(0.5) contrast(1.1) brightness(0.95)" },
  { id: "dramatic", name: "Dramatic", css: "contrast(1.3) saturate(1.2) brightness(0.9)" },
  { id: "pastel", name: "Pastel", css: "saturate(0.6) brightness(1.15) contrast(0.9)" },
  { id: "noir", name: "Noir", css: "grayscale(1) contrast(1.2)" },
  { id: "vivid", name: "Vivid", css: "saturate(1.8) contrast(1.1)" },
  { id: "dreamy", name: "Dreamy", css: "blur(0.5px) saturate(1.2) brightness(1.1)" },
  { id: "cyberpunk", name: "Cyberpunk", css: "saturate(2) hue-rotate(280deg) contrast(1.2)" },
];

export const CHANNEL_NAMES = [
  "StudyWithMe_Live", "FocusFlow_TV", "ProductivityStream",
  "DeepWork_Channel", "PomodoroPal", "ConcentrationStation",
  "QuietStudy_Room", "LibraryVibes", "CoffeeAndCode",
  "NightOwlStudies", "MorningGrind", "AfternoonFocus",
];

export const STREAM_TITLES = [
  "[no mic] study session | 2h pomodoro",
  "late night coding | no talking | chill vibes",
  "deep work session | pomodoro technique",
  "quiet study | reading & notes | lo-fi",
  "grinding assignments | 4h stream",
  "work with me | pomodoro 25/5 | no chat",
  "focus time | writing essay | silent stream",
  "study abroad prep | language learning",
  "exam prep marathon | day 3",
  "thesis writing | do not disturb",
];

export const TAGS = [
  "Just Chatting", "Study", "Productivity", "No Mic",
  "Pomodoro", "Deep Work", "Focus", "Chill",
  "Lo-fi", "Coding", "Reading", "Writing",
  "English", "ASMR", "Cozy", "Relaxing",
];
